apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanilla-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vanilla-shell
  template:
    metadata:
      labels:
        app: vanilla-shell
    spec:
      containers:
        - name: vanilla-shell
          image: vanilla-shell:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
