apiVersion: v1
kind: Service
metadata:
  name: vanilla-shell
spec:
  type: NodePort
  selector:
    app: vanilla-shell
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
